export const input = [
  // 'https://amzn.to/49obkgQ',
  // 'https://amzn.to/4bMQJEC',
  // 'https://amzn.to/3wtibXT',
  // 'https://amzn.to/3Tata16',
  // 'https://amzn.to/49Kas67',
  // 'https://amzn.to/3P09wCz',
  // 'https://amzn.to/49Ne1IQ',
  // 'https://amzn.to/42OKOL3',
  // 'https://amzn.to/49LFKta',
  // 'https://amzn.to/3SPBTVd',
  // 'https://amzn.to/49sQFYX',
  // 'https://amzn.to/3OR4jx2',
  // 'https://amzn.to/3SQ0068',
  // 'https://amzn.to/42M1S4x',
  // 'https://amzn.to/3wrzbxE',
  // 'https://amzn.to/49uVhOy',
  // 'https://amzn.to/3uBzbuB',
  // 'https://amzn.to/3UTjMAm',
  // 'https://amzn.to/4bT7Wwj',
  // 'https://amzn.to/3SRuS6f',
  // 'https://amzn.to/4bOYzxu',
  // 'https://amzn.to/3UN3Q2B',
  // 'https://amzn.to/42OL8tn',
  // 'https://amzn.to/3uMpHfW',
  // 'https://amzn.to/3OYM8pc',
  // "https://amzn.to/3Ijuvww",
  // "https://amzn.to/3UYz0UA",
  'https://amzn.to/3wGTUOh',
  'https://amzn.to/3T2aBLy',
  'https://amzn.to/3T4IpaT',
  'https://amzn.to/3V4AL2T',
  'https://amzn.to/3ToLenp',
  'https://amzn.to/3v5cAXd',
  'https://amzn.to/3uZSv4K',
  'https://amzn.to/3Ir5UFW'

]